preset: psr2

version: 8.1

finder:
  path:
    - "Neos.Cache/Classes"
    - "Neos.Cache/Tests"
    - "Neos.Eel/Classes"
    - "Neos.Eel/Tests"
    - "Neos.Error.Messages/Classes"
    - "Neos.Error.Messages/Tests"
    - "Neos.Flow/Classes"
    - "Neos.Flow/Tests"
    - "Neos.FluidAdaptor/Classes"
    - "Neos.FluidAdaptor/Tests"
    - "Neos.Kickstarter/Classes"
    - "Neos.Utility.Arrays/Classes"
    - "Neos.Utility.Arrays/Tests"
    - "Neos.Utility.Files/Classes"
    - "Neos.Utility.Files/Tests"
    - "Neos.Utility.Lock/Classes"
    - "Neos.Utility.Lock/Tests"
    - "Neos.Utility.MediaTypes/Classes"
    - "Neos.Utility.MediaTypes/Tests"
    - "Neos.Utility.ObjectHandling/Classes"
    - "Neos.Utility.ObjectHandling/Tests"
    - "Neos.Utility.OpcodeCache/Classes"
    - "Neos.Utility.Pdo/Classes"
    - "Neos.Utility.Schema/Classes"
    - "Neos.Utility.Schema/Tests"
    - "Neos.Utility.Unicode/Classes"
    - "Neos.Utility.Unicode/Tests"
  not-path:
    - "Neos.Eel/Classes/FlowQuery/FizzleParser.php"
    - "Neos.Eel/Classes/EelParser.php"
    - "Neos.Eel/Classes/AbstractParser.php"

enabled:
  - short_array_syntax
  - no_unused_imports
