<?php

declare(strict_types=1);

use Rector\CodeQuality\Rector\ClassMethod\OptionalParametersAfterRequiredRector;
use Rector\Config\RectorConfig;
use Rector\Php52\Rector\Switch_\ContinueToBreakInSwitchRector;
use Rector\Php55\Rector\String_\StringClassNameToClassConstantRector;
use Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector;
use Rector\Php73\Rector\FuncCall\ArrayKeyFirstLastRector;
use Rector\Php73\Rector\FuncCall\JsonThrowOnErrorRector;
use Rector\Php74\Rector\LNumber\AddLiteralSeparatorToNumberRector;
use Rector\Php74\Rector\MethodCall\ChangeReflectionTypeToStringToGetNameRector;
use Rector\Php74\Rector\Property\TypedPropertyRector;
use Rector\Php80\Rector\Class_\ClassPropertyAssignToConstructorPromotionRector;
use Rector\Php80\Rector\FuncCall\ClassOnObjectRector;
use Rector\Php80\Rector\FuncCall\TokenGetAllToObjectRector;
use Rector\Php80\Rector\FunctionLike\UnionTypesRector;
use Rector\Php80\Rector\Identical\StrEndsWithRector;
use Rector\Php80\Rector\Identical\StrStartsWithRector;
use Rector\Php80\Rector\NotIdentical\StrContainsRector;
use Rector\Php80\Rector\Switch_\ChangeSwitchToMatchRector;
use Rector\Set\ValueObject\LevelSetList;

return static function (RectorConfig $rectorConfig): void
{
    $rectorConfig->parallel();
    $rectorConfig->paths([
        __DIR__ . '/*/Classes',
        __DIR__ . '/*/Tests'
    ]);
    $rectorConfig->sets([LevelSetList::UP_TO_PHP_80]);
    $rectorConfig->skip([
        // the following rules are skipped because they caused trouble
        StringClassNameToClassConstantRector::class,
        RemoveExtraParametersRector::class,
        JsonThrowOnErrorRector::class,
        AddLiteralSeparatorToNumberRector::class,
        ChangeReflectionTypeToStringToGetNameRector::class,
        TypedPropertyRector::class,
        ArrayKeyFirstLastRector::class,
        ClassPropertyAssignToConstructorPromotionRector::class,
        UnionTypesRector::class,
        TokenGetAllToObjectRector::class,
        ClassOnObjectRector::class,
        ChangeSwitchToMatchRector::class,
        StrStartsWithRector::class,
        StrEndsWithRector::class,
        StrContainsRector::class,
        OptionalParametersAfterRequiredRector::class,

        // the autogenerated parsers have to be ignored
        __DIR__ . '/Neos.Eel/Classes/EelParser.php',
        __DIR__ . '/Neos.Eel/Classes/FlowQuery/FizzleParser.php'
    ]);
};
