<?php

declare(strict_types=1);

use Rector\Config\RectorConfig;
use Rector\Php71\Rector\FuncCall\RemoveExtraParametersRector;
use Rector\Set\ValueObject\LevelSetList;
use Rector\Php55\Rector\String_\StringClassNameToClassConstantRector;

return static function (RectorConfig $rectorConfig): void
{
    $rectorConfig->parallel();
    $rectorConfig->paths([
        __DIR__ . '/*/Classes',
        __DIR__ . '/*/Tests'
    ]);
    $rectorConfig->sets([LevelSetList::UP_TO_PHP_71]);
    $rectorConfig->skip([
        // the following rules are skipped because they caused trouble
        StringClassNameToClassConstantRector::class,
        RemoveExtraParametersRector::class,

        // the autogenerated parsers have to be ignored
        __DIR__ . '/Neos.Eel/Classes/EelParser.php',
        __DIR__ . '/Neos.Eel/Classes/FlowQuery/FizzleParser.php'
    ]);
};
