<?php

namespace Neos\Flow\ObjectManagement\DependencyInjection;

/*
 * This file is part of the Neos.Flow package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

use Neos\Flow\Annotations as Flow;
use Neos\Flow\Aop\ProxyInterface as AopProxyInterface;
use Neos\Flow\Cache\CacheManager;
use Neos\Flow\Configuration\ConfigurationManager;
use Neos\Flow\Configuration\Exception\InvalidConfigurationTypeException;
use Neos\Flow\Core\Bootstrap;
use Neos\Flow\Log\Utility\LogEnvironment;
use Neos\Flow\ObjectManagement\CompileTimeObjectManager;
use Neos\Flow\ObjectManagement\Configuration\Configuration;
use Neos\Flow\ObjectManagement\Configuration\ConfigurationArgument;
use Neos\Flow\ObjectManagement\Configuration\ConfigurationProperty;
use Neos\Flow\ObjectManagement\Exception as ObjectException;
use Neos\Flow\ObjectManagement\Exception\CannotBuildObjectException;
use Neos\Flow\ObjectManagement\Exception\UnknownObjectException;
use Neos\Flow\ObjectManagement\ObjectManagerInterface;
use Neos\Flow\ObjectManagement\Proxy\Compiler;
use Neos\Flow\ObjectManagement\Proxy\ObjectSerializationTrait;
use Neos\Flow\ObjectManagement\Proxy\ProxyClass;
use Neos\Flow\ObjectManagement\Proxy\ProxyMethodGenerator;
use Neos\Flow\Reflection\Exception\ClassLoadingForReflectionFailedException;
use Neos\Flow\Reflection\Exception\InvalidClassException;
use Neos\Flow\Reflection\MethodReflection;
use Neos\Flow\Reflection\ReflectionService;
use Neos\Utility\TypeHandling;
use Psr\Log\LoggerInterface;

/**
 * A Proxy Class Builder which integrates Dependency Injection
 */
#[Flow\Scope("singleton")]
#[Flow\Proxy(false)]
class ProxyClassBuilder
{
    public const AUTOGENERATED_PROXY_METHOD_COMMENT = 'Autogenerated Proxy Method';

    /**
     * @var array<Configuration>
     */
    protected array $objectConfigurations = [];

    /**
     * @param ReflectionService $reflectionService
     * @param Compiler $compiler
     * @param LoggerInterface $logger
     * @param ConfigurationManager $configurationManager
     * @param CacheManager $cacheManager
     * @param CompileTimeObjectManager<object> $objectManager
     */
    public function __construct(
        protected ReflectionService $reflectionService,
        protected Compiler $compiler,
        protected LoggerInterface $logger,
        protected ConfigurationManager $configurationManager,
        protected CacheManager $cacheManager,
        protected CompileTimeObjectManager $objectManager,
    ) {
    }

    /**
     * Analyzes the object configuration provided by the compile-time object manager and builds
     * the necessary PHP code for the proxy classes to realize dependency injection.
     *
     * @throws ObjectException
     * @throws CannotBuildObjectException
     * @throws UnknownObjectException
     * @throws ClassLoadingForReflectionFailedException
     * @throws InvalidClassException
     * @throws \ReflectionException
     */
    public function build(): void
    {
        $this->objectConfigurations = $this->objectManager->getObjectConfigurations();

        foreach ($this->objectConfigurations as $objectName => $objectConfiguration) {
            /** @var class-string $className */
            $className = $objectConfiguration->getClassName();
            if ($objectName !== $className
                || $this->compiler->hasCacheEntryForClass($className) === true
                || $this->reflectionService->isClassAbstract($className)
            ) {
                continue;
            }
            $proxyClass = $this->compiler->getProxyClass($className);
            if ($proxyClass === false) {
                continue;
            }
            $this->logger->debug(sprintf('Building dependency injection proxy for "%s"', $className), LogEnvironment::fromMethodName(__METHOD__));

            $injectionCodeWasIntroduced = false;

            $constructor = $proxyClass->getConstructor();

            $wakeupMethod = $proxyClass->getMethod('__wakeup');
            $wakeupMethod->setDocBlock(self::AUTOGENERATED_PROXY_METHOD_COMMENT);

            $wakeupMethod->addPostParentCallCode($this->buildLifecycleInitializationCode($objectConfiguration, ObjectManagerInterface::INITIALIZATIONCAUSE_RECREATED));
            $wakeupMethod->addPostParentCallCode($this->buildLifecycleShutdownCode($objectConfiguration, ObjectManagerInterface::INITIALIZATIONCAUSE_RECREATED));

            $injectPropertiesCode = $this->buildPropertyInjectionCode($objectConfiguration);
            if ($injectPropertiesCode !== []) {
                $injectionCodeWasIntroduced = true;
                $proxyClass->addTraits(['\\' . PropertyInjectionTrait::class]);
                $injectPropertiesMethod = $proxyClass->getMethod('Flow_Proxy_injectProperties');
                $injectPropertiesMethod->addPreParentCallCode(implode(PHP_EOL, $injectPropertiesCode));
                $injectPropertiesMethod->setVisibility(ProxyMethodGenerator::VISIBILITY_PRIVATE);
                $injectPropertiesMethod->setDocBlock(self::AUTOGENERATED_PROXY_METHOD_COMMENT);

                $wakeupMethod->addPreParentCallCode(
                    <<<'PHP'
                $this->Flow_Proxy_injectProperties();
                PHP
                );
                $constructor->addPostParentCallCode(
                    <<<PHP
                if (\\{$className}::class === get_class(\$this)) {
                    \$this->Flow_Proxy_injectProperties();
                }
                PHP
                );
            }

            $couldHaveEntityRelations = $this->couldHaveEntityRelations($objectConfiguration);
            $isProxyWithAop = in_array('\\' . AopProxyInterface::class, $proxyClass->getInterfaces());
            $serializeRelatedEntitiesCode = $this->buildSerializeRelatedEntitiesCode($objectConfiguration, $isProxyWithAop || $injectionCodeWasIntroduced);
            if ($serializeRelatedEntitiesCode !== '') {
                $proxyClass->addTraits(['\\' . ObjectSerializationTrait::class]);
                if ($couldHaveEntityRelations) {
                    $proxyClass->addProperty('Flow_Persistence_RelatedEntitiesContainer', null, 'private readonly \Neos\Flow\ObjectManagement\Proxy\RelatedEntitiesContainer');
                    $constructor->addPostParentCallCode('$this->Flow_Persistence_RelatedEntitiesContainer = new \Neos\Flow\ObjectManagement\Proxy\RelatedEntitiesContainer();');
                }

                $classHasSleepMethod = $this->reflectionService->hasMethod($className, '__sleep');
                if (!$classHasSleepMethod) {
                    $sleepMethod = $proxyClass->getMethod('__sleep');
                    $sleepMethod->setDocBlock(self::AUTOGENERATED_PROXY_METHOD_COMMENT);
                    $sleepMethod->addPostParentCallCode($serializeRelatedEntitiesCode);
                }
                $wakeupMethod->addPreParentCallCode($this->buildSetRelatedEntitiesCode());
            }

            $constructor->addPostParentCallCode($this->buildLifecycleInitializationCode($objectConfiguration, ObjectManagerInterface::INITIALIZATIONCAUSE_CREATED));
            $constructor->addPostParentCallCode($this->buildLifecycleShutdownCode($objectConfiguration, ObjectManagerInterface::INITIALIZATIONCAUSE_CREATED));

            if ($this->objectManager->getContext()->isProduction() || $this->objectManager->getContext()->isTesting()) {
                $this->compileStaticMethods($className, $proxyClass);
            }
        }
    }

    /**
     * Renders code to create identifier/type information from related entities in an object.
     *
     * The code is only rendered if one of the following conditions is met:
     *
     *   - The class is annotated with Entity
     *   - The class is annotated with Scope("session")
     *   - The class has properties annotated with Transient
     *   - The class has properties annotated with Inject
     *
     * Despite the previous condition, the code will not be rendered if the following condition is true:
     *
     *   - The class already has a __sleep() method (we assume that the developer wants to take care of serialization themself)
     *
     * NOTE: Even though the method name suggests that it is only dealing with related entities code, it is currently also
     *       used for removing injected properties before serialization. This should be refactored in the future.
     */
    protected function buildSerializeRelatedEntitiesCode(Configuration $objectConfiguration, bool $forceSerializationCode): string
    {
        $className = $objectConfiguration->getClassName();
        if ($className == '') {
            return '';
        }
        $forceSerializationCode = $forceSerializationCode === false ? ($this->reflectionService->getClassAnnotation($className, Flow\Proxy::class)?->forceSerializationCode ?? false) : true;
        $scopeAnnotation = $this->reflectionService->getClassAnnotation($className, Flow\Scope::class);
        $transientProperties = $this->reflectionService->getPropertyNamesByAnnotation($className, Flow\Transient::class);
        $injectedProperties = $this->reflectionService->getPropertyNamesByAnnotation($className, Flow\Inject::class);

        $doBuildCode = $this->reflectionService->getClassAnnotation($className, Flow\Entity::class) !== null;
        $doBuildCode = $doBuildCode || (count($transientProperties) > 0);
        $doBuildCode = $doBuildCode || (count($injectedProperties) > 0);
        $doBuildCode = $doBuildCode || ($scopeAnnotation && $scopeAnnotation->value === 'session');

        if (!$forceSerializationCode && $doBuildCode === false) {
            return '';
        }

        $propertyVarTags = [];
        foreach ($this->reflectionService->getPropertyNamesByTag($className, 'var') as $propertyName) {
            $varTagValues = $this->reflectionService->getPropertyTagValues($className, $propertyName, 'var');
            $propertyVarTags[$propertyName] = $varTagValues[0] ?? null;
        }

        if (!$forceSerializationCode && count($transientProperties) === 0 && count($propertyVarTags) === 0) {
            return '';
        }

        return str_replace(
            ['{{transientPropertiesArrayCode}}', '{{propertyVarTagsArrayCode}}'],
            [
                var_export($transientProperties, true),
                var_export($propertyVarTags, true)
            ],
            <<<'PHP'
            $result = $this->Flow_serializeRelatedEntities({{transientPropertiesArrayCode}}, {{propertyVarTagsArrayCode}});
            PHP
        );
    }

    protected function buildSetRelatedEntitiesCode(): string
    {
        return PHP_EOL . '$this->Flow_setRelatedEntities();' . PHP_EOL;
    }

    /**
     * Builds the code necessary to inject setter based dependencies.
     *
     * @return string[] php code
     * @throws UnknownObjectException
     */
    protected function buildPropertyInjectionCode(Configuration $objectConfiguration): array
    {
        $commands = [];
        $injectedProperties = [];
        foreach ($objectConfiguration->getProperties() as $propertyName => $propertyConfiguration) {
            assert($propertyConfiguration instanceof ConfigurationProperty);
            if ($propertyConfiguration->getAutowiring() === Configuration::AUTOWIRING_MODE_OFF) {
                continue;
            }

            $propertyValue = $propertyConfiguration->getValue();
            switch ($propertyConfiguration->getType()) {
                case ConfigurationProperty::PROPERTY_TYPES_OBJECT:
                    if ($propertyValue instanceof Configuration) {
                        $commands[] = implode(PHP_EOL, $this->buildPropertyInjectionCodeByConfiguration($objectConfiguration, $propertyName, $propertyValue));
                    } else {
                        $commands[] = implode(PHP_EOL, $this->buildPropertyInjectionCodeByString($objectConfiguration, $propertyConfiguration, $propertyName, $propertyValue));
                    }

                    break;
                case ConfigurationProperty::PROPERTY_TYPES_STRAIGHTVALUE:
                    $preparedSetterArgument = var_export($propertyValue, true);
                    $commands[] = 'if (\Neos\Utility\ObjectAccess::setProperty($this, \'' . $propertyName . '\', ' . $preparedSetterArgument . ') === false) { $this->' . $propertyName . ' = ' . $preparedSetterArgument . ';}';
                    break;
                case ConfigurationProperty::PROPERTY_TYPES_CONFIGURATION:
                    $configurationType = $propertyValue['type'];
                    if (!in_array($configurationType, $this->configurationManager->getAvailableConfigurationTypes(), true)) {
                        throw new UnknownObjectException('The configuration injection specified for property "' . $propertyName . '" in the object configuration of object "' . $objectConfiguration->getObjectName() . '" refers to the unknown configuration type "' . $configurationType . '".', 1420736211);
                    }
                    $commands = array_merge($commands, $this->buildPropertyInjectionCodeByConfigurationTypeAndPath($objectConfiguration, $propertyName, $configurationType, $propertyValue['path']));
                    break;
                case ConfigurationProperty::PROPERTY_TYPES_CACHE:
                    $cacheIdentifier = $propertyValue['identifier'];
                    if (!array_key_exists($cacheIdentifier, $this->cacheManager->getCacheConfigurations())) {
                        throw new UnknownObjectException('The cache injection specified for property "' . $propertyName . '" in the object configuration of object "' . $objectConfiguration->getObjectName() . '" refers to the unknown cache identifier "' . $cacheIdentifier . '".', 1701280300);
                    }
                    $commands = array_merge($commands, $this->buildPropertyInjectionCodeByCacheIdentifier($objectConfiguration, $propertyName, $cacheIdentifier));
                    break;
            }
            $injectedProperties[] = $propertyName;
        }

        if (count($commands) > 0) {
            $commands[] = '$this->Flow_Injected_Properties = ' . var_export($injectedProperties, true) . ";" . PHP_EOL;
        }

        return $commands;
    }

    /**
     * Builds code which injects an object which was specified by its object configuration
     *
     * @param Configuration $objectConfiguration Configuration of the object to inject into
     * @param string $propertyName Name of the property to inject
     * @param Configuration $propertyConfiguration Configuration of the object to inject
     * @return string[] lines of PHP code
     * @throws UnknownObjectException
     * @throws InvalidConfigurationTypeException
     */
    protected function buildPropertyInjectionCodeByConfiguration(Configuration $objectConfiguration, $propertyName, Configuration $propertyConfiguration): array
    {
        $className = $objectConfiguration->getClassName();
        $propertyObjectName = $propertyConfiguration->getObjectName();
        $propertyClassName = $propertyConfiguration->getClassName();
        if ($propertyConfiguration->getFactoryObjectName()) {
            $preparedSetterArgument = $this->buildCustomFactoryCall($propertyConfiguration->getFactoryObjectName(), $propertyConfiguration->getFactoryMethodName(), $propertyConfiguration->getFactoryArguments());
        } else {
            if (!isset($this->objectConfigurations[$propertyClassName])) {
                $configurationSource = $objectConfiguration->getConfigurationSourceHint();
                throw new UnknownObjectException('Unknown class "' . $propertyClassName . '", specified as property "' . $propertyName . '" in the object configuration of object "' . $objectConfiguration->getObjectName() . '" (' . $configurationSource . ').', 1296130876);
            }
            if ($this->objectConfigurations[$propertyClassName]->getScope() === Configuration::SCOPE_PROTOTYPE) {
                $preparedSetterArgument = 'new \\' . $propertyClassName . '(' . $this->buildMethodParametersCode($propertyConfiguration->getArguments()) . ')';
            } else {
                $preparedSetterArgument = $this->buildStaticObjectManagerCode($propertyClassName);
            }
        }

        if ($className !== '') {
            $result = $this->buildSetterInjectionCode($className, $propertyName, $preparedSetterArgument);
            if ($result !== null) {
                return $result;
            }
        }

        return $this->buildLazyPropertyInjectionCode($propertyObjectName, $propertyClassName, $propertyName, $preparedSetterArgument);
    }

    /**
     * Builds code which injects an object which was specified by its object name
     *
     * @param Configuration $objectConfiguration Configuration of the object to inject into
     * @param ConfigurationProperty $propertyConfiguration
     * @param string $propertyName Name of the property to inject
     * @param string $propertyObjectName Object name of the object to inject
     * @return string[] lines of PHP code
     * @throws UnknownObjectException
     * @throws InvalidConfigurationTypeException
     */
    public function buildPropertyInjectionCodeByString(Configuration $objectConfiguration, ConfigurationProperty $propertyConfiguration, string $propertyName, string $propertyObjectName): array
    {
        $className = $objectConfiguration->getClassName();
        if ($className === '') {
            throw new \Exception(sprintf("Empty classname configuration for object %s", $objectConfiguration->getObjectName()), 1784273303);
        }
        if (!isset($this->objectConfigurations[$propertyObjectName])) {
            $configurationSource = $objectConfiguration->getConfigurationSourceHint();
            if (!isset($propertyObjectName[0])) {
                throw new UnknownObjectException(sprintf('Malformed DocComment block for property %s in class %s.', $propertyName, $className), 1360171313);
            }
            if ($propertyObjectName[0] === '\\') {
                throw new UnknownObjectException('The object name "' . $propertyObjectName . '" which was specified as a property in the object configuration of object "' . $objectConfiguration->getObjectName() . '" (' . $configurationSource . ') starts with a leading backslash.', 1277827579);
            }
            throw new UnknownObjectException('The object "' . $propertyObjectName . '" which was specified as a property in the object configuration of object "' . $objectConfiguration->getObjectName() . '" (' . $configurationSource . ') does not exist. Check for spelling mistakes and if that dependency is correctly configured.', 1265213849);
        }
        $propertyClassName = $this->objectConfigurations[$propertyObjectName]->getClassName();
        if ($this->objectConfigurations[$propertyObjectName]->getScope() === Configuration::SCOPE_PROTOTYPE && !$this->objectConfigurations[$propertyObjectName]->isCreatedByFactory()) {
            $preparedSetterArgument = 'new \\' . $propertyClassName . '(' . $this->buildMethodParametersCode($this->objectConfigurations[$propertyObjectName]->getArguments()) . ')';
        } else {
            $preparedSetterArgument = $this->buildStaticObjectManagerCode($propertyObjectName);
        }

        $result = $this->buildSetterInjectionCode($className, $propertyName, $preparedSetterArgument);
        if ($result !== null) {
            return $result;
        }

        # Disable lazy property injection, see https://github.com/neos/flow-development-collection/issues/2114
        if ($propertyConfiguration->isLazyLoading() && $this->objectConfigurations[$propertyObjectName]->getScope() !== Configuration::SCOPE_PROTOTYPE) {
            return $this->buildLazyPropertyInjectionCode($propertyObjectName, $propertyClassName, $propertyName, $preparedSetterArgument);
        }

        return ['$this->' . $propertyName . ' = ' . $preparedSetterArgument . ';'];
    }

    /**
     * Builds code which assigns the value stored in the specified configuration into the given class property.
     *
     * @param Configuration $objectConfiguration Configuration of the object to inject into
     * @param string $propertyName Name of the property to inject
     * @param string $configurationType the configuration type of the injected property (one of the ConfigurationManager::CONFIGURATION_TYPE_* constants)
     * @param string|null $configurationPath Path with "." as separator specifying the setting value to inject or NULL if the complete configuration array should be injected
     * @return string[] PHP code
     */
    public function buildPropertyInjectionCodeByConfigurationTypeAndPath(Configuration $objectConfiguration, string  $propertyName, string $configurationType, ?string $configurationPath = null): array
    {
        $className = $objectConfiguration->getClassName();
        $preparedSetterArgument = $this->buildStaticObjectManagerCode(ConfigurationManager::class) . '->getConfiguration(\'' . $configurationType . '\'';
        if ($configurationPath !== null) {
            $preparedSetterArgument .= ', \'' . $configurationPath . '\'';
        }
        $preparedSetterArgument .= ')';
        if ($className !== '') {
            $result = $this->buildSetterInjectionCode($className, $propertyName, $preparedSetterArgument);
            if ($result !== null) {
                return $result;
            }
        }
        return ['$this->' . $propertyName . ' = ' . $preparedSetterArgument . ';'];
    }

    /**
     * Builds code which assigns the frontend of the specified cache into the given class property.
     *
     * @param Configuration $objectConfiguration Configuration of the object to inject into
     * @param string $propertyName Name of the property to inject
     * @param string $cacheIdentifier the identifier of the cache to inject
     * @return string[] PHP code
     */
    public function buildPropertyInjectionCodeByCacheIdentifier(Configuration $objectConfiguration, string $propertyName, string $cacheIdentifier): array
    {
        $className = $objectConfiguration->getClassName();
        $preparedSetterArgument = $this->buildStaticObjectManagerCode(CacheManager::class) . '->getCache(\'' . $cacheIdentifier . '\')';
        if ($className !== '') {
            $result = $this->buildSetterInjectionCode($className, $propertyName, $preparedSetterArgument);
            if ($result !== null) {
                return $result;
            }
        }
        return ['$this->' . $propertyName . ' = ' . $preparedSetterArgument . ';'];
    }

    /**
     * Builds code which injects a DependencyProxy instead of the actual dependency
     *
     * @param string $propertyObjectName Object name of the dependency to inject
     * @param string $propertyClassName Class name of the dependency to inject
     * @param string $propertyName Name of the property in the class to inject into
     * @param string $preparedSetterArgument PHP code to use for retrieving the value to inject
     * @return string[] PHP code
     */
    protected function buildLazyPropertyInjectionCode(string $propertyObjectName, string $propertyClassName, string $propertyName, string $preparedSetterArgument): array
    {
        $setterArgumentHash = "'" . md5($preparedSetterArgument) . "'";
        $commands[] = '$this->Flow_Proxy_LazyPropertyInjection(\'' . $propertyObjectName . '\', \'' . $propertyClassName . '\', \'' . $propertyName . '\', ' . $setterArgumentHash . ', function() { return ' . $preparedSetterArgument . '; });';

        return $commands;
    }

    /**
     * Builds a code snippet which tries to inject the specified property first through calling the related
     * inject*() method and then the set*() method. If neither exists and the property doesn't exist either,
     * an empty array is returned.
     *
     * If neither inject*() nor set*() exists, but the property does exist, NULL is returned
     *
     * @param class-string $className Name of the class to inject into
     * @param string $propertyName Name of the property to inject
     * @param string $preparedSetterArgument PHP code to use for retrieving the value to inject
     *
     * @return null|string[] PHP code
     *
     * @phpstan-return array{0?: string}|null
     */
    protected function buildSetterInjectionCode(string $className, string $propertyName, string $preparedSetterArgument): array|null
    {
        $setterMethodName = 'inject' . ucfirst($propertyName);
        if ($this->reflectionService->hasMethod($className, $setterMethodName)) {
            return ['$this->' . $setterMethodName . '(' . $preparedSetterArgument . ');'];
        }
        $setterMethodName = 'set' . ucfirst($propertyName);
        if ($this->reflectionService->hasMethod($className, $setterMethodName)) {
            return ['$this->' . $setterMethodName . '(' . $preparedSetterArgument . ');'];
        }
        if (!property_exists($className, $propertyName)) {
            return [];
        }
        return null;
    }

    /**
     * Builds code which calls the lifecycle initialization method, if any.
     *
     * @param Configuration $objectConfiguration
     * @param int $cause a ObjectManagerInterface::INITIALIZATIONCAUSE_* constant which is the cause of the initialization command being called.
     * @return string
     */
    protected function buildLifecycleInitializationCode(Configuration $objectConfiguration, int $cause): string
    {
        $lifecycleInitializationMethodName = $objectConfiguration->getLifecycleInitializationMethodName();
        $className = $objectConfiguration->getClassName();
        if ($className === '') {
            return '';
        }
        if (!$this->reflectionService->hasMethod($className, $lifecycleInitializationMethodName)) {
            return '';
        }

        $lifeCycleCode = '    $this->' . $lifecycleInitializationMethodName . '(' . $cause . ');';
        return implode(PHP_EOL, $this->wrapLifeCycleChecksCode($className, $lifeCycleCode, $cause));
    }

    /**
     * Builds code which registers the lifecycle shutdown method, if any.
     *
     * @param Configuration $objectConfiguration
     * @param int $cause a ObjectManagerInterface::INITIALIZATIONCAUSE_* constant which is the cause of the initialization command being called.
     * @return string
     */
    protected function buildLifecycleShutdownCode(Configuration $objectConfiguration, int $cause): string
    {
        $lifecycleShutdownMethodName = $objectConfiguration->getLifecycleShutdownMethodName();
        $className = $objectConfiguration->getClassName();
        if ($className === '') {
            return '';
        }
        if (!$this->reflectionService->hasMethod($className, $lifecycleShutdownMethodName)) {
            return '';
        }

        $lifeCycleCode = '    \Neos\Flow\Core\Bootstrap::$staticObjectManager->registerShutdownObject($this, \'' . $lifecycleShutdownMethodName . '\');';
        return implode(PHP_EOL, $this->wrapLifeCycleChecksCode($objectConfiguration->getClassName(), $lifeCycleCode, $cause));
    }

    /**
     * @param string $className
     * @param string $lifeCycleCode
     * @param int $cause
     * @return string[]
     */
    protected function wrapLifeCycleChecksCode(string $className, string $lifeCycleCode, int $cause): array
    {
        $codeLines = [];
        $codeLines[] = '$isSameClass = get_class($this) === \\' . $className . '::class;';
        if ($cause === ObjectManagerInterface::INITIALIZATIONCAUSE_RECREATED) {
            $codeLines[] = '$classParents = class_parents($this);';
            $codeLines[] = '$classImplements = class_implements($this);';
            $codeLines[] = '$isClassProxy = array_search(\\' . $className . '::class, $classParents) !== false && array_search(\\Doctrine\Persistence\Proxy::class, $classImplements) !== false;';
            $codeLines[] = 'if ($isSameClass || $isClassProxy) {';
        } else {
            $codeLines[] = 'if ($isSameClass) {';
        }
        $codeLines[] = $lifeCycleCode;
        $codeLines[] = '}';
        return $codeLines;
    }

    /**
     * @param array<int, ?ConfigurationArgument> $argumentConfigurations
     * @throws InvalidConfigurationTypeException
     */
    protected function buildMethodParametersCode(array $argumentConfigurations): string
    {
        $preparedArguments = [];

        foreach ($argumentConfigurations as $argument) {
            if ($argument === null) {
                $preparedArguments[] = 'NULL';
            } else {
                $argumentValue = $argument->getValue();
                switch ($argument->getType()) {
                    case ConfigurationArgument::ARGUMENT_TYPES_OBJECT:
                        if ($argumentValue instanceof Configuration) {
                            $argumentValueObjectName = $argumentValue->getObjectName();
                            if ($this->objectConfigurations[$argumentValueObjectName]->getScope() === Configuration::SCOPE_PROTOTYPE) {
                                $preparedArguments[] = 'new \\' . $argumentValueObjectName . '(' . $this->buildMethodParametersCode($argumentValue->getArguments()) . ')';
                            } else {
                                $preparedArguments[] = $this->buildStaticObjectManagerCode($argumentValueObjectName);
                            }
                        } else {
                            if (str_contains($argumentValue, '.')) {
                                $argumentValue = $this->configurationManager->getConfiguration(ConfigurationManager::CONFIGURATION_TYPE_SETTINGS, $argumentValue);
                            }
                            $preparedArguments[] = $this->buildStaticObjectManagerCode($argumentValue);
                        }
                        break;

                    case ConfigurationArgument::ARGUMENT_TYPES_STRAIGHTVALUE:
                        $preparedArguments[] = var_export($argumentValue, true);
                        break;

                    case ConfigurationArgument::ARGUMENT_TYPES_SETTING:
                        $preparedArguments[] = $this->buildStaticObjectManagerCode(ConfigurationManager::class) . '->getConfiguration(\Neos\Flow\Configuration\ConfigurationManager::CONFIGURATION_TYPE_SETTINGS, \'' . $argumentValue . '\')';
                        break;
                }
            }
        }
        return implode(', ', $preparedArguments);
    }

    /**
     * @param string $customFactoryObjectName
     * @param array<int, ?ConfigurationArgument> $arguments
     * @throws InvalidConfigurationTypeException
     */
    protected function buildCustomFactoryCall(string $customFactoryObjectName, string $customFactoryMethodName, array $arguments): string
    {
        $parametersCode = $this->buildMethodParametersCode($arguments);
        return ($customFactoryObjectName ? $this->buildStaticObjectManagerCode($customFactoryObjectName) . '->' : '') . $customFactoryMethodName . '(' . $parametersCode . ')';
    }

    /**
     * Compile the result of methods marked with CompileStatic into the proxy class
     *
     * @param class-string $className
     * @param ProxyClass $proxyClass
     * @return void
     * @throws ClassLoadingForReflectionFailedException
     * @throws InvalidClassException
     * @throws ObjectException
     * @throws \ReflectionException
     */
    protected function compileStaticMethods(string $className, ProxyClass $proxyClass): void
    {
        $methodNames = $this->reflectionService->getMethodsAnnotatedWith($className, Flow\CompileStatic::class);
        foreach ($methodNames as $methodName) {
            if (!$this->reflectionService->isMethodStatic($className, $methodName)) {
                throw new ObjectException(sprintf('The method %s:%s() is annotated CompileStatic so it must be static', $className, $methodName), 1476348303);
            }
            if ($this->reflectionService->isMethodPrivate($className, $methodName)) {
                throw new ObjectException(sprintf('The method %s:%s() is annotated CompileStatic so it must not be private', $className, $methodName), 1476348306);
            }
            $reflectedMethod = new MethodReflection($className, $methodName);
            $value = $reflectedMethod->invoke(null, $this->objectManager);
            $compiledResult = var_export($value, true);

            $compiledMethod = $proxyClass->getMethod($methodName);
            $compiledMethod->setBody('return ' . $compiledResult . ';');
        }
    }

    protected function couldHaveEntityRelations(Configuration $objectConfiguration): bool
    {
        $result = false;
        /** @var class-string $className */
        $className = $objectConfiguration->getClassName();
        $classPropertyNames = $this->reflectionService->getClassPropertyNames($className);
        foreach ($classPropertyNames as $propertyName) {
            if (
                $this->reflectionService->isPropertyAnnotatedWith($className, $propertyName, Flow\Transient::class) ||
                $this->reflectionService->isPropertyAnnotatedWith($className, $propertyName, Flow\Inject::class)
            ) {
                continue;
            }
            $propertyType = $this->reflectionService->getPropertyType($className, $propertyName);
            if ($propertyType === null) {
                $propertyType = $this->reflectionService->getPropertyTagValues($className, $propertyName, 'var')[0] ?? null;
            }
            if ($propertyType === null) {
                continue;
            }

            try {
                $typeInformation = TypeHandling::parseType($propertyType);
            } catch (\Throwable $throwable) {
                // we will skip on unparsable types
                continue;
            }
            if (
                TypeHandling::isSimpleType($typeInformation['type']) ||
                ($typeInformation['elementType'] !== null && TypeHandling::isSimpleType($typeInformation['elementType']))
            ) {
                continue;
            }

            if ($typeInformation['type'] === \Closure::class) {
                continue;
            }

            if (!class_exists($typeInformation['type'])) {
                continue;
            }

            $isEntity = $this->reflectionService->isClassReflected($typeInformation['type']) &&
                $this->reflectionService->getClassAnnotation($typeInformation['type'], Flow\Entity::class);
            if (!$isEntity) {
                continue;
            }

            foreach ($objectConfiguration->getProperties() as $propertyConfiguration) {
                if ($propertyConfiguration->getName() === $propertyName) {
                    continue 2;
                }
            }

            $this->logger->info('Class ' . $className . ' has property ' . $propertyName . ' that might be entity!');
            $result = true;
        }

        return $result;
    }

    protected function buildStaticObjectManagerCode(string $objectName): string
    {
        // we could do something like "$objectName . '::class'" here, but
        // it might reference a virtual object, so this neds to stay a string.
        return '\\' . Bootstrap::class . '::$staticObjectManager->get(\'' . $objectName . '\')';
    }
}
