#!/usr/bin/env php
<?php

/*                                                                        *
 * This script belongs to the Flow framework.                             *
 *                                                                        *
 * It is free software; you can redistribute it and/or modify it under    *
 * the terms of the MIT license.                                          *
 *                                                                        */

/**
 * Bootstrap for the command line
 */

require(__DIR__ . '/Packages/Framework/TYPO3.Flow/Scripts/flow.php');

?>