#!/usr/bin/env php
<?php

/*
 * This file is part of the Neos.Flow package.
 *
 * (c) Contributors of the Neos Project - www.neos.io
 *
 * This package is Open Source Software. For the full copyright and license
 * information, please view the LICENSE file which was distributed with this
 * source code.
 */

/**
 * Bootstrap for the command line
 */

require(__DIR__ . '/Packages/Framework/Neos.Flow/Scripts/flow.php');

?>
