#
# Package configuration for the Flow Framework
#

Neos:
  Flow:
    package:
      # This can be used to make packages inactive, even though they would be
      # activated automatically otherwise.
      inactiveByDefault:
        - 'neos.composerplugin'
        - 'Composer.Installers'
      # Option for the PackageManager::Create to map the packagesPath by package type
      packagesPathByType:
        'typo3-flow-package': 'Application'
        'neos-package': 'Application'
        'typo3-flow-framework': 'Framework'
        'neos-framework': 'Framework'
