#
# Resource configuration for the Flow Framework
#

Neos:
  Flow:
    resource:
      # A list of filename extensions that must not be uploaded through the resource
      # management.
      uploadExtensionBlacklist: &uploadExtensionBlacklist
        'aspx': TRUE
        'cgi': TRUE
        'php3': TRUE
        'php4': TRUE
        'php5': TRUE
        'phtml': TRUE
        'php': TRUE
        'pl': TRUE
        'py': TRUE
        'pyc': TRUE
        'pyo': TRUE
        'rb': TRUE

      # Definition of resource storages provided by the Flow core.
      # Storages are used for storing and retrieving resources.
      storages:

        #
        defaultPersistentResourcesStorage:
          storage: 'Neos\Flow\ResourceManagement\Storage\WritableFileSystemStorage'
          storageOptions:
            path: '%FLOW_PATH_DATA%Persistent/Resources/'

        #
        defaultStaticResourcesStorage:
          storage: 'Neos\Flow\ResourceManagement\Storage\PackageStorage'

      # Definition of the default resource collections.
      # Collections are used to bundle / group static or persistent resources
      # for common processing and publication.
      collections:

        # Collection which contains all static resources
        static:
          storage: 'defaultStaticResourcesStorage'
          target: 'localWebDirectoryStaticResourcesTarget'
          pathPatterns:
            - '*/Resources/Public/'
            - '*/Resources/Public/*'

        # Collection which contains all persistent resources
        persistent:
          storage: 'defaultPersistentResourcesStorage'
          target: 'localWebDirectoryPersistentResourcesTarget'

      # Definition of the basic resource publication targets.
      targets:

        # Target for publishing static resources to the local web directory
        localWebDirectoryStaticResourcesTarget:
          target: 'Neos\Flow\ResourceManagement\Target\FileSystemSymlinkTarget'
          targetOptions:
            path: '%FLOW_PATH_WEB%_Resources/Static/Packages/'
            baseUri: '_Resources/Static/Packages/'
            extensionBlacklist: *uploadExtensionBlacklist

            # If the symlinks should be relative instead of absolute
            #relativeSymlinks: false

        # Target for publishing persistent resources to the local web directory
        localWebDirectoryPersistentResourcesTarget:
          target: 'Neos\Flow\ResourceManagement\Target\FileSystemSymlinkTarget'
          targetOptions:
            path: '%FLOW_PATH_WEB%_Resources/Persistent/'
            baseUri: '_Resources/Persistent/'
            extensionBlacklist: *uploadExtensionBlacklist

            # If the generated URI path segment containing the sha1 should be divided into multiple segments (recommended if you expect many resources):
            subdivideHashPathSegment: false

            # If the symlinks should be relative instead of absolute
            #relativeSymlinks: false
